package alkalus.main.asm.transformer;

import static org.objectweb.asm.Opcodes.*;

import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;

public class ClassTransformer_Witchery_TileEntityWitchesCauldron extends BaseTransformer {

	public ClassTransformer_Witchery_TileEntityWitchesCauldron(String transformedName, byte[] basicClass, boolean isObf) {
		super(transformedName, basicClass, isObf);
		init();
	}

	public String aMinecraftServer = "net/minecraft/server/MinecraftServer";
	
	public final String aEntity = mObf ? "sa" : "net/minecraft/entity/Entity";	
	public final String aEntityPlayer = mObf ? "yz" : "net/minecraft/entity/player/EntityPlayer";
	public final String aWorld = mObf ? "ahb" : "net/minecraft/world/World";
	public final String aTileEntity = mObf ? "aor" : "net/minecraft/tileentity/TileEntity";	
	public final String aNBTBase = mObf ? "dy" : "net/minecraft/nbt/NBTBase";	
	public final String aNBTTagCompound = mObf ? "dh" : "net/minecraft/nbt/NBTTagCompound";
	public final String aNBTTagList = mObf ? "dq" : "net/minecraft/nbt/NBTTagList";
	public final String aBlock = mObf ? "aji" : "net/minecraft/block/Block";
	public final String aEntityLivingBase = mObf ? "sv" : "net/minecraft/entity/EntityLivingBase";
	public final String aAxisAlignedBB = mObf ? "azt" : "net/minecraft/util/AxisAlignedBB";	
	public final String aItemStack = mObf ? "add" : "net/minecraft/item/ItemStack";
	public final String aEntityItem = mObf ? "xk" : "net/minecraft/entity/item/EntityItem";	

	public boolean injectMethod(String aMethodName, ClassWriter cw) {
		boolean[] aResults = new boolean[1];		
		aResults[0] = inject_updateEntity();
		for (boolean b : aResults) {
			if (!b) {
				log("Patching failed.");
				return false;
			}
		}	
		log("Patching Success.");	
		return true;
	}

	private boolean inject_updateEntity() {
		MethodVisitor mv;
		mv = getWriter().visitMethod(ACC_PUBLIC, "updateEntity", "()V", null, null);
		mv.visitCode();
		Label l0 = new Label();
		mv.visitLabel(l0);
		mv.visitLineNumber(94, l0);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKESPECIAL, "com/emoniph/witchery/blocks/TileEntityBase", "updateEntity", "()V", false);
		Label l1 = new Label();
		mv.visitLabel(l1);
		mv.visitLineNumber(95, l1);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitFieldInsn(GETFIELD, ""+aWorld+"", "isRemote", "Z");
		Label l2 = new Label();
		mv.visitJumpInsn(IFNE, l2);
		Label l3 = new Label();
		mv.visitLabel(l3);
		mv.visitLineNumber(96, l3);
		mv.visitInsn(ICONST_0);
		mv.visitVarInsn(ISTORE, 1);
		Label l4 = new Label();
		mv.visitLabel(l4);
		mv.visitLineNumber(97, l4);
		mv.visitTypeInsn(NEW, "alkalus/main/core/util/BlockPos");
		mv.visitInsn(DUP);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitMethodInsn(INVOKESPECIAL, "alkalus/main/core/util/BlockPos", "<init>", "(IIIL"+aWorld+";)V", false);
		mv.visitVarInsn(ASTORE, 2);
		Label l5 = new Label();
		mv.visitLabel(l5);
		mv.visitLineNumber(98, l5);
		mv.visitVarInsn(ALOAD, 2);
		mv.visitMethodInsn(INVOKESTATIC, "alkalus/main/core/util/CauldronUtils", "hasFireBeneath", "(Lalkalus/main/core/util/BlockPos;)Z", false);
		Label l6 = new Label();
		mv.visitJumpInsn(IFEQ, l6);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "isFilled", "()Z", false);
		mv.visitJumpInsn(IFEQ, l6);
		Label l7 = new Label();
		mv.visitLabel(l7);
		mv.visitLineNumber(99, l7);
		mv.visitVarInsn(ALOAD, 2);
		mv.visitMethodInsn(INVOKEVIRTUAL, "alkalus/main/core/util/BlockPos", "getDown", "()Lalkalus/main/core/util/BlockPos;", false);
		mv.visitMethodInsn(INVOKESTATIC, "alkalus/main/core/util/CauldronUtils", "getFireHeatLevel", "(Lalkalus/main/core/util/BlockPos;)I", false);
		mv.visitVarInsn(ISTORE, 3);
		Label l8 = new Label();
		mv.visitLabel(l8);
		mv.visitLineNumber(100, l8);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ticksHeated", "I");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/brewing/TileEntityCauldron", "TICKS_TO_BOIL", "I");
		Label l9 = new Label();
		mv.visitJumpInsn(IF_ICMPGE, l9);
		Label l10 = new Label();
		mv.visitLabel(l10);
		mv.visitLineNumber(101, l10);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(DUP);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ticksHeated", "I");
		mv.visitVarInsn(ILOAD, 3);
		mv.visitInsn(IADD);
		mv.visitInsn(DUP_X1);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ticksHeated", "I");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/brewing/TileEntityCauldron", "TICKS_TO_BOIL", "I");
		mv.visitMethodInsn(INVOKESTATIC, "java/lang/Math", "min", "(II)I", false);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ticksHeated", "I");
		Label l11 = new Label();
		mv.visitLabel(l11);
		mv.visitLineNumber(102, l11);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ticksHeated", "I");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/brewing/TileEntityCauldron", "TICKS_TO_BOIL", "I");
		mv.visitJumpInsn(IF_ICMPNE, l9);
		Label l12 = new Label();
		mv.visitLabel(l12);
		mv.visitLineNumber(103, l12);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 1);
		Label l13 = new Label();
		mv.visitLabel(l13);
		mv.visitLineNumber(106, l13);
		mv.visitJumpInsn(GOTO, l9);
		mv.visitLabel(l6);
		mv.visitLineNumber(107, l6);
		mv.visitFrame(Opcodes.F_APPEND,2, new Object[] {Opcodes.INTEGER, "alkalus/main/core/util/BlockPos"}, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ticksHeated", "I");
		mv.visitJumpInsn(IFLE, l9);
		Label l14 = new Label();
		mv.visitLabel(l14);
		mv.visitLineNumber(108, l14);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ticksHeated", "I");
		Label l15 = new Label();
		mv.visitLabel(l15);
		mv.visitLineNumber(109, l15);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 1);
		mv.visitLabel(l9);
		mv.visitLineNumber(111, l9);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "isBoiling", "()Z", false);
		Label l16 = new Label();
		mv.visitJumpInsn(IFEQ, l16);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ticks", "J");
		mv.visitLdcInsn(new Long(20L));
		mv.visitInsn(LREM);
		mv.visitLdcInsn(new Long(7L));
		mv.visitInsn(LCMP);
		mv.visitJumpInsn(IFNE, l16);
		Label l17 = new Label();
		mv.visitLabel(l17);
		mv.visitLineNumber(112, l17);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "powered", "Z");
		mv.visitVarInsn(ISTORE, 3);
		Label l18 = new Label();
		mv.visitLabel(l18);
		mv.visitLineNumber(113, l18);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "getPower", "()I", false);
		mv.visitVarInsn(ISTORE, 4);
		Label l19 = new Label();
		mv.visitLabel(l19);
		mv.visitLineNumber(114, l19);
		mv.visitVarInsn(ILOAD, 4);
		Label l20 = new Label();
		mv.visitJumpInsn(IFNE, l20);
		Label l21 = new Label();
		mv.visitLabel(l21);
		mv.visitLineNumber(115, l21);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_1);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "powered", "Z");
		Label l22 = new Label();
		mv.visitLabel(l22);
		mv.visitLineNumber(116, l22);
		Label l23 = new Label();
		mv.visitJumpInsn(GOTO, l23);
		mv.visitLabel(l20);
		mv.visitLineNumber(117, l20);
		mv.visitFrame(Opcodes.F_APPEND,2, new Object[] {Opcodes.INTEGER, Opcodes.INTEGER}, 0, null);
		mv.visitVarInsn(ILOAD, 4);
		Label l24 = new Label();
		mv.visitJumpInsn(IFLE, l24);
		Label l25 = new Label();
		mv.visitLabel(l25);
		mv.visitLineNumber(118, l25);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/common/PowerSources", "findClosestPowerSource", "(L"+aTileEntity+";)Lcom/emoniph/witchery/common/IPowerSource;", false);
		mv.visitVarInsn(ASTORE, 5);
		Label l26 = new Label();
		mv.visitLabel(l26);
		mv.visitLineNumber(120, l26);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "tank", "Lnet/minecraftforge/fluids/FluidTank;");
		mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fluids/FluidTank", "getFluid", "()Lnet/minecraftforge/fluids/FluidStack;", false);
		Label l27 = new Label();
		mv.visitJumpInsn(IFNULL, l27);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "tank", "Lnet/minecraftforge/fluids/FluidTank;");
		mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fluids/FluidTank", "getFluid", "()Lnet/minecraftforge/fluids/FluidStack;", false);
		mv.visitFieldInsn(GETFIELD, "net/minecraftforge/fluids/FluidStack", "tag", "L"+aNBTTagCompound+";");
		mv.visitJumpInsn(IFNULL, l27);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "tank", "Lnet/minecraftforge/fluids/FluidTank;");
		mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fluids/FluidTank", "getFluidAmount", "()I", false);
		mv.visitIntInsn(SIPUSH, 3000);
		mv.visitJumpInsn(IF_ICMPNE, l27);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "tank", "Lnet/minecraftforge/fluids/FluidTank;");
		mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fluids/FluidTank", "getFluid", "()Lnet/minecraftforge/fluids/FluidStack;", false);
		mv.visitFieldInsn(GETFIELD, "net/minecraftforge/fluids/FluidStack", "tag", "L"+aNBTTagCompound+";");
		mv.visitLdcInsn("RitualTriggered");
		mv.visitMethodInsn(INVOKEVIRTUAL, ""+aNBTTagCompound+"", "getBoolean", "(Ljava/lang/String;)Z", false);
		mv.visitJumpInsn(IFEQ, l27);
		Label l28 = new Label();
		mv.visitLabel(l28);
		mv.visitLineNumber(121, l28);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/Witchery", "Blocks", "Lcom/emoniph/witchery/WitcheryBlocks;");
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/WitcheryBlocks", "GLYPH_RITUAL", "L"+aBlock+";");
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/util/CircleUtil", "isSmallCircle", "(L"+aWorld+";IIIL"+aBlock+";)Z", false);
		mv.visitVarInsn(ISTORE, 8);
		Label l29 = new Label();
		mv.visitLabel(l29);
		mv.visitLineNumber(122, l29);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/Witchery", "Blocks", "Lcom/emoniph/witchery/WitcheryBlocks;");
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/WitcheryBlocks", "GLYPH_INFERNAL", "L"+aBlock+";");
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/util/CircleUtil", "isSmallCircle", "(L"+aWorld+";IIIL"+aBlock+";)Z", false);
		mv.visitVarInsn(ISTORE, 9);
		Label l30 = new Label();
		mv.visitLabel(l30);
		mv.visitLineNumber(123, l30);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/Witchery", "Blocks", "Lcom/emoniph/witchery/WitcheryBlocks;");
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/WitcheryBlocks", "GLYPH_RITUAL", "L"+aBlock+";");
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/util/CircleUtil", "isMediumCircle", "(L"+aWorld+";IIIL"+aBlock+";)Z", false);
		mv.visitVarInsn(ISTORE, 10);
		Label l31 = new Label();
		mv.visitLabel(l31);
		mv.visitLineNumber(124, l31);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/Witchery", "Blocks", "Lcom/emoniph/witchery/WitcheryBlocks;");
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/WitcheryBlocks", "GLYPH_INFERNAL", "L"+aBlock+";");
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/util/CircleUtil", "isMediumCircle", "(L"+aWorld+";IIIL"+aBlock+";)Z", false);
		mv.visitVarInsn(ISTORE, 11);
		Label l32 = new Label();
		mv.visitLabel(l32);
		mv.visitLineNumber(125, l32);
		mv.visitLdcInsn(new Double("1.4"));
		mv.visitVarInsn(DSTORE, 12);
		Label l33 = new Label();
		mv.visitLabel(l33);
		mv.visitLineNumber(126, l33);
		mv.visitVarInsn(ILOAD, 8);
		Label l34 = new Label();
		mv.visitJumpInsn(IFEQ, l34);
		Label l35 = new Label();
		mv.visitLabel(l35);
		mv.visitLineNumber(127, l35);
		mv.visitVarInsn(DLOAD, 12);
		mv.visitLdcInsn(new Double("0.2"));
		mv.visitInsn(DSUB);
		mv.visitVarInsn(DSTORE, 12);
		mv.visitLabel(l34);
		mv.visitLineNumber(129, l34);
		mv.visitFrame(Opcodes.F_FULL, 13, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, Opcodes.INTEGER, "com/emoniph/witchery/common/IPowerSource", Opcodes.TOP, Opcodes.TOP, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.DOUBLE}, 0, new Object[] {});
		mv.visitVarInsn(ILOAD, 10);
		Label l36 = new Label();
		mv.visitJumpInsn(IFEQ, l36);
		Label l37 = new Label();
		mv.visitLabel(l37);
		mv.visitLineNumber(130, l37);
		mv.visitVarInsn(DLOAD, 12);
		mv.visitLdcInsn(new Double("0.2"));
		mv.visitInsn(DSUB);
		mv.visitVarInsn(DSTORE, 12);
		mv.visitLabel(l36);
		mv.visitLineNumber(132, l36);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ILOAD, 9);
		Label l38 = new Label();
		mv.visitJumpInsn(IFEQ, l38);
		Label l39 = new Label();
		mv.visitLabel(l39);
		mv.visitLineNumber(133, l39);
		mv.visitVarInsn(DLOAD, 12);
		mv.visitLdcInsn(new Double("0.37"));
		mv.visitInsn(DSUB);
		mv.visitVarInsn(DSTORE, 12);
		mv.visitLabel(l38);
		mv.visitLineNumber(135, l38);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ILOAD, 11);
		Label l40 = new Label();
		mv.visitJumpInsn(IFEQ, l40);
		Label l41 = new Label();
		mv.visitLabel(l41);
		mv.visitLineNumber(136, l41);
		mv.visitVarInsn(DLOAD, 12);
		mv.visitLdcInsn(new Double("0.37"));
		mv.visitInsn(DSUB);
		mv.visitVarInsn(DSTORE, 12);
		mv.visitLabel(l40);
		mv.visitLineNumber(138, l40);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ILOAD, 4);
		mv.visitInsn(I2D);
		mv.visitVarInsn(DLOAD, 12);
		mv.visitInsn(DMUL);
		mv.visitVarInsn(DSTORE, 6);
		Label l42 = new Label();
		mv.visitLabel(l42);
		mv.visitLineNumber(139, l42);
		Label l43 = new Label();
		mv.visitJumpInsn(GOTO, l43);
		mv.visitLabel(l27);
		mv.visitLineNumber(141, l27);
		mv.visitFrame(Opcodes.F_FULL, 6, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, Opcodes.INTEGER, "com/emoniph/witchery/common/IPowerSource"}, 0, new Object[] {});
		mv.visitVarInsn(ILOAD, 4);
		mv.visitInsn(I2D);
		mv.visitVarInsn(DSTORE, 6);
		mv.visitLabel(l43);
		mv.visitLineNumber(143, l43);
		mv.visitFrame(Opcodes.F_APPEND,1, new Object[] {Opcodes.DOUBLE}, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitVarInsn(ILOAD, 4);
		Label l44 = new Label();
		mv.visitJumpInsn(IFEQ, l44);
		mv.visitVarInsn(ALOAD, 5);
		Label l45 = new Label();
		mv.visitJumpInsn(IFNULL, l45);
		mv.visitVarInsn(DLOAD, 6);
		mv.visitVarInsn(ALOAD, 5);
		mv.visitMethodInsn(INVOKEINTERFACE, "com/emoniph/witchery/common/IPowerSource", "getCurrentPower", "()F", true);
		mv.visitInsn(F2D);
		mv.visitInsn(DCMPG);
		mv.visitJumpInsn(IFLE, l44);
		mv.visitLabel(l45);
		mv.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron"});
		mv.visitInsn(ICONST_0);
		Label l46 = new Label();
		mv.visitJumpInsn(GOTO, l46);
		mv.visitLabel(l44);
		mv.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron"});
		mv.visitInsn(ICONST_1);
		mv.visitLabel(l46);
		mv.visitFrame(Opcodes.F_FULL, 7, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, Opcodes.INTEGER, "com/emoniph/witchery/common/IPowerSource", Opcodes.DOUBLE}, 2, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER});
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "powered", "Z");
		Label l47 = new Label();
		mv.visitLabel(l47);
		mv.visitLineNumber(144, l47);
		mv.visitJumpInsn(GOTO, l23);
		mv.visitLabel(l24);
		mv.visitLineNumber(146, l24);
		mv.visitFrame(Opcodes.F_CHOP,2, null, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "powered", "Z");
		mv.visitLabel(l23);
		mv.visitLineNumber(148, l23);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ILOAD, 3);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "powered", "Z");
		mv.visitJumpInsn(IF_ICMPEQ, l16);
		Label l48 = new Label();
		mv.visitLabel(l48);
		mv.visitLineNumber(149, l48);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 1);
		mv.visitLabel(l16);
		mv.visitLineNumber(152, l16);
		mv.visitFrame(Opcodes.F_CHOP,2, null, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ticks", "J");
		mv.visitLdcInsn(new Long(10L));
		mv.visitInsn(LREM);
		mv.visitLdcInsn(new Long(8L));
		mv.visitInsn(LCMP);
		Label l49 = new Label();
		mv.visitJumpInsn(IFNE, l49);
		Label l50 = new Label();
		mv.visitLabel(l50);
		mv.visitLineNumber(153, l50);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ritualTicks", "I");
		mv.visitVarInsn(ISTORE, 3);
		Label l51 = new Label();
		mv.visitLabel(l51);
		mv.visitLineNumber(155, l51);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "isBoiling", "()Z", false);
		Label l52 = new Label();
		mv.visitJumpInsn(IFEQ, l52);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "isPowered", "()Z", false);
		mv.visitJumpInsn(IFEQ, l52);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "tank", "Lnet/minecraftforge/fluids/FluidTank;");
		mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fluids/FluidTank", "getFluid", "()Lnet/minecraftforge/fluids/FluidStack;", false);
		mv.visitJumpInsn(IFNULL, l52);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "tank", "Lnet/minecraftforge/fluids/FluidTank;");
		mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fluids/FluidTank", "getFluid", "()Lnet/minecraftforge/fluids/FluidStack;", false);
		mv.visitFieldInsn(GETFIELD, "net/minecraftforge/fluids/FluidStack", "tag", "L"+aNBTTagCompound+";");
		mv.visitJumpInsn(IFNULL, l52);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "tank", "Lnet/minecraftforge/fluids/FluidTank;");
		mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fluids/FluidTank", "getFluidAmount", "()I", false);
		mv.visitIntInsn(SIPUSH, 3000);
		mv.visitJumpInsn(IF_ICMPNE, l52);
		Label l53 = new Label();
		mv.visitLabel(l53);
		mv.visitLineNumber(156, l53);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "tank", "Lnet/minecraftforge/fluids/FluidTank;");
		mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fluids/FluidTank", "getFluid", "()Lnet/minecraftforge/fluids/FluidStack;", false);
		mv.visitFieldInsn(GETFIELD, "net/minecraftforge/fluids/FluidStack", "tag", "L"+aNBTTagCompound+";");
		mv.visitVarInsn(ASTORE, 4);
		Label l54 = new Label();
		mv.visitLabel(l54);
		mv.visitLineNumber(157, l54);
		mv.visitVarInsn(ALOAD, 4);
		mv.visitLdcInsn("RitualTriggered");
		mv.visitMethodInsn(INVOKEVIRTUAL, ""+aNBTTagCompound+"", "getBoolean", "(Ljava/lang/String;)Z", false);
		Label l55 = new Label();
		mv.visitJumpInsn(IFEQ, l55);
		Label l56 = new Label();
		mv.visitLabel(l56);
		mv.visitLineNumber(158, l56);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(DUP);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ritualTicks", "I");
		mv.visitInsn(ICONST_1);
		mv.visitInsn(IADD);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ritualTicks", "I");
		Label l57 = new Label();
		mv.visitLabel(l57);
		mv.visitLineNumber(159, l57);
		mv.visitInsn(ICONST_0);
		mv.visitVarInsn(ISTORE, 5);
		Label l58 = new Label();
		mv.visitLabel(l58);
		mv.visitLineNumber(160, l58);
		mv.visitLdcInsn(Type.getType("Lcom/emoniph/witchery/entity/EntityCovenWitch;"));
		mv.visitVarInsn(ALOAD, 0);
		mv.visitLdcInsn(new Double("6.0"));
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/util/EntityUtil", "getEntitiesInRadius", "(Ljava/lang/Class;L"+aTileEntity+";D)Ljava/util/List;", false);
		mv.visitVarInsn(ASTORE, 6);
		Label l59 = new Label();
		mv.visitLabel(l59);
		mv.visitLineNumber(161, l59);
		mv.visitVarInsn(ALOAD, 6);
		mv.visitMethodInsn(INVOKEINTERFACE, "java/util/List", "iterator", "()Ljava/util/Iterator;", true);
		mv.visitVarInsn(ASTORE, 8);
		Label l60 = new Label();
		mv.visitJumpInsn(GOTO, l60);
		Label l61 = new Label();
		mv.visitLabel(l61);
		mv.visitFrame(Opcodes.F_FULL, 9, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, ""+aNBTTagCompound+"", Opcodes.INTEGER, "java/util/List", Opcodes.TOP, "java/util/Iterator"}, 0, new Object[] {});
		mv.visitVarInsn(ALOAD, 8);
		mv.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
		mv.visitTypeInsn(CHECKCAST, "com/emoniph/witchery/entity/EntityCovenWitch");
		mv.visitVarInsn(ASTORE, 7);
		Label l62 = new Label();
		mv.visitLabel(l62);
		mv.visitLineNumber(162, l62);
		mv.visitVarInsn(ALOAD, 7);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/entity/EntityCovenWitch", "getOwner", "()L"+aEntityLivingBase+";", false);
		mv.visitJumpInsn(IFNULL, l60);
		Label l63 = new Label();
		mv.visitLabel(l63);
		mv.visitLineNumber(163, l63);
		mv.visitIincInsn(5, 1);
		mv.visitLabel(l60);
		mv.visitLineNumber(161, l60);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ALOAD, 8);
		mv.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
		mv.visitJumpInsn(IFNE, l61);
		Label l64 = new Label();
		mv.visitLabel(l64);
		mv.visitLineNumber(166, l64);
		mv.visitLdcInsn(Type.getType("L"+aEntityPlayer+";"));
		mv.visitVarInsn(ALOAD, 0);
		mv.visitLdcInsn(new Double("6.0"));
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/util/EntityUtil", "getEntitiesInRadius", "(Ljava/lang/Class;L"+aTileEntity+";D)Ljava/util/List;", false);
		mv.visitVarInsn(ASTORE, 7);
		Label l65 = new Label();
		mv.visitLabel(l65);
		mv.visitLineNumber(167, l65);
		mv.visitInsn(ICONST_0);
		mv.visitVarInsn(ISTORE, 8);
		Label l66 = new Label();
		mv.visitLabel(l66);
		mv.visitLineNumber(168, l66);
		mv.visitVarInsn(ALOAD, 7);
		mv.visitMethodInsn(INVOKEINTERFACE, "java/util/List", "iterator", "()Ljava/util/Iterator;", true);
		mv.visitVarInsn(ASTORE, 10);
		Label l67 = new Label();
		mv.visitJumpInsn(GOTO, l67);
		Label l68 = new Label();
		mv.visitLabel(l68);
		mv.visitFrame(Opcodes.F_FULL, 11, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, ""+aNBTTagCompound+"", Opcodes.INTEGER, "java/util/List", "java/util/List", Opcodes.INTEGER, Opcodes.TOP, "java/util/Iterator"}, 0, new Object[] {});
		mv.visitVarInsn(ALOAD, 10);
		mv.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
		mv.visitTypeInsn(CHECKCAST, ""+aEntityPlayer+"");
		mv.visitVarInsn(ASTORE, 9);
		Label l69 = new Label();
		mv.visitLabel(l69);
		mv.visitLineNumber(169, l69);
		mv.visitVarInsn(ALOAD, 9);
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/entity/EntityCovenWitch", "getCovenSize", "(L"+aEntityPlayer+";)I", false);
		mv.visitJumpInsn(IFLE, l67);
		Label l70 = new Label();
		mv.visitLabel(l70);
		mv.visitLineNumber(170, l70);
		mv.visitVarInsn(ILOAD, 8);
		Label l71 = new Label();
		mv.visitJumpInsn(IFEQ, l71);
		Label l72 = new Label();
		mv.visitLabel(l72);
		mv.visitLineNumber(171, l72);
		mv.visitIincInsn(5, 1);
		Label l73 = new Label();
		mv.visitLabel(l73);
		mv.visitLineNumber(172, l73);
		mv.visitJumpInsn(GOTO, l67);
		mv.visitLabel(l71);
		mv.visitLineNumber(174, l71);
		mv.visitFrame(Opcodes.F_FULL, 11, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, ""+aNBTTagCompound+"", Opcodes.INTEGER, "java/util/List", "java/util/List", Opcodes.INTEGER, ""+aEntityPlayer+"", "java/util/Iterator"}, 0, new Object[] {});
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 8);
		mv.visitLabel(l67);
		mv.visitLineNumber(168, l67);
		mv.visitFrame(Opcodes.F_FULL, 11, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, ""+aNBTTagCompound+"", Opcodes.INTEGER, "java/util/List", "java/util/List", Opcodes.INTEGER, Opcodes.TOP, "java/util/Iterator"}, 0, new Object[] {});
		mv.visitVarInsn(ALOAD, 10);
		mv.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
		mv.visitJumpInsn(IFNE, l68);
		Label l74 = new Label();
		mv.visitLabel(l74);
		mv.visitLineNumber(178, l74);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ritualTicks", "I");
		mv.visitIntInsn(BIPUSH, 20);
		mv.visitJumpInsn(IF_ICMPLE, l55);
		Label l75 = new Label();
		mv.visitLabel(l75);
		mv.visitLineNumber(179, l75);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/common/PowerSources", "findClosestPowerSource", "(L"+aTileEntity+";)Lcom/emoniph/witchery/common/IPowerSource;", false);
		mv.visitVarInsn(ASTORE, 9);
		Label l76 = new Label();
		mv.visitLabel(l76);
		mv.visitLineNumber(180, l76);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "getPower", "()I", false);
		mv.visitVarInsn(ISTORE, 10);
		Label l77 = new Label();
		mv.visitLabel(l77);
		mv.visitLineNumber(181, l77);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/Witchery", "Blocks", "Lcom/emoniph/witchery/WitcheryBlocks;");
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/WitcheryBlocks", "GLYPH_RITUAL", "L"+aBlock+";");
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/util/CircleUtil", "isSmallCircle", "(L"+aWorld+";IIIL"+aBlock+";)Z", false);
		mv.visitVarInsn(ISTORE, 11);
		Label l78 = new Label();
		mv.visitLabel(l78);
		mv.visitLineNumber(182, l78);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/Witchery", "Blocks", "Lcom/emoniph/witchery/WitcheryBlocks;");
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/WitcheryBlocks", "GLYPH_INFERNAL", "L"+aBlock+";");
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/util/CircleUtil", "isSmallCircle", "(L"+aWorld+";IIIL"+aBlock+";)Z", false);
		mv.visitVarInsn(ISTORE, 12);
		Label l79 = new Label();
		mv.visitLabel(l79);
		mv.visitLineNumber(183, l79);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/Witchery", "Blocks", "Lcom/emoniph/witchery/WitcheryBlocks;");
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/WitcheryBlocks", "GLYPH_RITUAL", "L"+aBlock+";");
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/util/CircleUtil", "isMediumCircle", "(L"+aWorld+";IIIL"+aBlock+";)Z", false);
		mv.visitVarInsn(ISTORE, 13);
		Label l80 = new Label();
		mv.visitLabel(l80);
		mv.visitLineNumber(184, l80);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/Witchery", "Blocks", "Lcom/emoniph/witchery/WitcheryBlocks;");
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/WitcheryBlocks", "GLYPH_INFERNAL", "L"+aBlock+";");
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/util/CircleUtil", "isMediumCircle", "(L"+aWorld+";IIIL"+aBlock+";)Z", false);
		mv.visitVarInsn(ISTORE, 14);
		Label l81 = new Label();
		mv.visitLabel(l81);
		mv.visitLineNumber(185, l81);
		mv.visitLdcInsn(new Double("1.4"));
		mv.visitVarInsn(DSTORE, 15);
		Label l82 = new Label();
		mv.visitLabel(l82);
		mv.visitLineNumber(186, l82);
		mv.visitVarInsn(ILOAD, 11);
		Label l83 = new Label();
		mv.visitJumpInsn(IFEQ, l83);
		Label l84 = new Label();
		mv.visitLabel(l84);
		mv.visitLineNumber(187, l84);
		mv.visitVarInsn(DLOAD, 15);
		mv.visitLdcInsn(new Double("0.2"));
		mv.visitInsn(DSUB);
		mv.visitVarInsn(DSTORE, 15);
		mv.visitLabel(l83);
		mv.visitLineNumber(189, l83);
		mv.visitFrame(Opcodes.F_FULL, 16, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, ""+aNBTTagCompound+"", Opcodes.INTEGER, "java/util/List", "java/util/List", Opcodes.INTEGER, "com/emoniph/witchery/common/IPowerSource", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.DOUBLE}, 0, new Object[] {});
		mv.visitVarInsn(ILOAD, 13);
		Label l85 = new Label();
		mv.visitJumpInsn(IFEQ, l85);
		Label l86 = new Label();
		mv.visitLabel(l86);
		mv.visitLineNumber(190, l86);
		mv.visitVarInsn(DLOAD, 15);
		mv.visitLdcInsn(new Double("0.2"));
		mv.visitInsn(DSUB);
		mv.visitVarInsn(DSTORE, 15);
		mv.visitLabel(l85);
		mv.visitLineNumber(192, l85);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitInsn(ICONST_0);
		mv.visitVarInsn(ISTORE, 17);
		Label l87 = new Label();
		mv.visitLabel(l87);
		mv.visitLineNumber(193, l87);
		mv.visitVarInsn(ILOAD, 11);
		Label l88 = new Label();
		mv.visitJumpInsn(IFNE, l88);
		mv.visitVarInsn(ILOAD, 13);
		mv.visitJumpInsn(IFNE, l88);
		Label l89 = new Label();
		mv.visitLabel(l89);
		mv.visitLineNumber(194, l89);
		mv.visitIincInsn(17, 1);
		mv.visitLabel(l88);
		mv.visitLineNumber(196, l88);
		mv.visitFrame(Opcodes.F_APPEND,1, new Object[] {Opcodes.INTEGER}, 0, null);
		mv.visitVarInsn(ILOAD, 12);
		Label l90 = new Label();
		mv.visitJumpInsn(IFEQ, l90);
		Label l91 = new Label();
		mv.visitLabel(l91);
		mv.visitLineNumber(197, l91);
		mv.visitIincInsn(17, 1);
		Label l92 = new Label();
		mv.visitLabel(l92);
		mv.visitLineNumber(198, l92);
		mv.visitVarInsn(DLOAD, 15);
		mv.visitLdcInsn(new Double("0.37"));
		mv.visitInsn(DSUB);
		mv.visitVarInsn(DSTORE, 15);
		mv.visitLabel(l90);
		mv.visitLineNumber(200, l90);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ILOAD, 14);
		Label l93 = new Label();
		mv.visitJumpInsn(IFEQ, l93);
		Label l94 = new Label();
		mv.visitLabel(l94);
		mv.visitLineNumber(201, l94);
		mv.visitIincInsn(17, 1);
		Label l95 = new Label();
		mv.visitLabel(l95);
		mv.visitLineNumber(202, l95);
		mv.visitVarInsn(DLOAD, 15);
		mv.visitLdcInsn(new Double("0.37"));
		mv.visitInsn(DSUB);
		mv.visitVarInsn(DSTORE, 15);
		mv.visitLabel(l93);
		mv.visitLineNumber(204, l93);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ILOAD, 10);
		Label l96 = new Label();
		mv.visitJumpInsn(IFEQ, l96);
		mv.visitVarInsn(ALOAD, 9);
		Label l97 = new Label();
		mv.visitJumpInsn(IFNULL, l97);
		mv.visitVarInsn(ALOAD, 9);
		mv.visitVarInsn(ILOAD, 10);
		mv.visitInsn(I2D);
		mv.visitVarInsn(DLOAD, 15);
		mv.visitInsn(DMUL);
		mv.visitMethodInsn(INVOKESTATIC, "java/lang/Math", "floor", "(D)D", false);
		mv.visitInsn(D2I);
		mv.visitInsn(I2F);
		mv.visitMethodInsn(INVOKEINTERFACE, "com/emoniph/witchery/common/IPowerSource", "consumePower", "(F)Z", true);
		mv.visitJumpInsn(IFEQ, l97);
		mv.visitLabel(l96);
		mv.visitLineNumber(206, l96);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("16.0"));
		mv.visitInsn(DSUB);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("16.0"));
		mv.visitInsn(DSUB);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("16.0"));
		mv.visitInsn(DSUB);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("16.0"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("16.0"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("16.0"));
		mv.visitInsn(DADD);
		mv.visitMethodInsn(INVOKESTATIC, ""+aAxisAlignedBB+"", "getBoundingBox", "(DDDDDD)L"+aAxisAlignedBB+";", false);
		mv.visitVarInsn(ASTORE, 18);
		Label l98 = new Label();
		mv.visitLabel(l98);
		mv.visitLineNumber(207, l98);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitLdcInsn(Type.getType("Lcom/emoniph/witchery/entity/EntityLeonard;"));
		mv.visitVarInsn(ALOAD, 18);
		mv.visitMethodInsn(INVOKEVIRTUAL, ""+aWorld+"", "getEntitiesWithinAABB", "(Ljava/lang/Class;L"+aAxisAlignedBB+";)Ljava/util/List;", false);
		mv.visitVarInsn(ASTORE, 19);
		Label l99 = new Label();
		mv.visitLabel(l99);
		mv.visitLineNumber(208, l99);
		mv.visitInsn(ICONST_0);
		mv.visitVarInsn(ISTORE, 20);
		Label l100 = new Label();
		mv.visitLabel(l100);
		mv.visitLineNumber(209, l100);
		mv.visitVarInsn(ALOAD, 19);
		mv.visitMethodInsn(INVOKEINTERFACE, "java/util/List", "iterator", "()Ljava/util/Iterator;", true);
		mv.visitVarInsn(ASTORE, 22);
		Label l101 = new Label();
		mv.visitJumpInsn(GOTO, l101);
		Label l102 = new Label();
		mv.visitLabel(l102);
		mv.visitFrame(Opcodes.F_FULL, 22, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, ""+aNBTTagCompound+"", Opcodes.INTEGER, "java/util/List", "java/util/List", Opcodes.INTEGER, "com/emoniph/witchery/common/IPowerSource", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.DOUBLE, Opcodes.INTEGER, ""+aAxisAlignedBB+"", "java/util/List", Opcodes.INTEGER, Opcodes.TOP, "java/util/Iterator"}, 0, new Object[] {});
		mv.visitVarInsn(ALOAD, 22);
		mv.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
		mv.visitTypeInsn(CHECKCAST, "com/emoniph/witchery/entity/EntityLeonard");
		mv.visitVarInsn(ASTORE, 21);
		Label l103 = new Label();
		mv.visitLabel(l103);
		mv.visitLineNumber(210, l103);
		mv.visitVarInsn(ALOAD, 21);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/entity/EntityLeonard", "isDead", "Z");
		mv.visitJumpInsn(IFNE, l101);
		mv.visitVarInsn(ALOAD, 21);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/entity/EntityLeonard", "getHealth", "()F", false);
		mv.visitInsn(FCONST_1);
		mv.visitInsn(FCMPL);
		mv.visitJumpInsn(IFLE, l101);
		Label l104 = new Label();
		mv.visitLabel(l104);
		mv.visitLineNumber(211, l104);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 20);
		Label l105 = new Label();
		mv.visitLabel(l105);
		mv.visitLineNumber(212, l105);
		Label l106 = new Label();
		mv.visitJumpInsn(GOTO, l106);
		mv.visitLabel(l101);
		mv.visitLineNumber(209, l101);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ALOAD, 22);
		mv.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
		mv.visitJumpInsn(IFNE, l102);
		mv.visitLabel(l106);
		mv.visitLineNumber(215, l106);
		mv.visitFrame(Opcodes.F_FULL, 20, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, ""+aNBTTagCompound+"", Opcodes.INTEGER, "java/util/List", "java/util/List", Opcodes.INTEGER, "com/emoniph/witchery/common/IPowerSource", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.DOUBLE, Opcodes.INTEGER, ""+aAxisAlignedBB+"", "java/util/List", Opcodes.INTEGER}, 0, new Object[] {});
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/brewing/WitcheryBrewRegistry", "INSTANCE", "Lcom/emoniph/witchery/brewing/WitcheryBrewRegistry;");
		mv.visitMethodInsn(INVOKESTATIC, ""+aMinecraftServer+"", "getServer", "()L"+aMinecraftServer+";", false);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitVarInsn(ALOAD, 4);
		mv.visitVarInsn(ILOAD, 5);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ritualTicks", "I");
		mv.visitIntInsn(BIPUSH, 20);
		mv.visitInsn(ISUB);
		mv.visitVarInsn(ILOAD, 20);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/WitcheryBrewRegistry", "updateRitual", "(L"+aMinecraftServer+";L"+aWorld+";IIIL"+aNBTTagCompound+";IIZ)Lcom/emoniph/witchery/brewing/RitualStatus;", false);
		mv.visitVarInsn(ASTORE, 21);
		Label l107 = new Label();
		mv.visitLabel(l107);
		mv.visitLineNumber(216, l107);
		mv.visitInsn(ICONST_0);
		mv.visitVarInsn(ISTORE, 22);
		Label l108 = new Label();
		mv.visitLabel(l108);
		mv.visitLineNumber(217, l108);
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/brewing/TileEntityCauldron", "$SWITCH_TABLE$com$emoniph$witchery$brewing$RitualStatus", "()[I", false);
		mv.visitVarInsn(ALOAD, 21);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/RitualStatus", "ordinal", "()I", false);
		mv.visitInsn(IALOAD);
		Label l109 = new Label();
		Label l110 = new Label();
		Label l111 = new Label();
		Label l112 = new Label();
		Label l113 = new Label();
		Label l114 = new Label();
		Label l115 = new Label();
		mv.visitTableSwitchInsn(1, 6, l115, new Label[] { l109, l110, l111, l112, l113, l114 });
		mv.visitLabel(l110);
		mv.visitLineNumber(219, l110);
		mv.visitFrame(Opcodes.F_APPEND,2, new Object[] {"com/emoniph/witchery/brewing/RitualStatus", Opcodes.INTEGER}, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitVarInsn(ILOAD, 17);
		mv.visitVarInsn(ILOAD, 20);
		Label l116 = new Label();
		mv.visitJumpInsn(IFEQ, l116);
		mv.visitInsn(ICONST_1);
		Label l117 = new Label();
		mv.visitJumpInsn(GOTO, l117);
		mv.visitLabel(l116);
		mv.visitFrame(Opcodes.F_FULL, 22, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, ""+aNBTTagCompound+"", Opcodes.INTEGER, "java/util/List", "java/util/List", Opcodes.INTEGER, "com/emoniph/witchery/common/IPowerSource", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.DOUBLE, Opcodes.INTEGER, ""+aAxisAlignedBB+"", "java/util/List", Opcodes.INTEGER, "com/emoniph/witchery/brewing/RitualStatus", Opcodes.INTEGER}, 2, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER});
		mv.visitInsn(ICONST_0);
		mv.visitLabel(l117);
		mv.visitFrame(Opcodes.F_FULL, 22, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, ""+aNBTTagCompound+"", Opcodes.INTEGER, "java/util/List", "java/util/List", Opcodes.INTEGER, "com/emoniph/witchery/common/IPowerSource", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.DOUBLE, Opcodes.INTEGER, ""+aAxisAlignedBB+"", "java/util/List", Opcodes.INTEGER, "com/emoniph/witchery/brewing/RitualStatus", Opcodes.INTEGER}, 3, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, Opcodes.INTEGER});
		mv.visitInsn(IADD);
		mv.visitVarInsn(ILOAD, 10);
		mv.visitMethodInsn(INVOKESPECIAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "checkForMisfortune", "(II)V", false);
		Label l118 = new Label();
		mv.visitLabel(l118);
		mv.visitLineNumber(220, l118);
		mv.visitJumpInsn(GOTO, l115);
		mv.visitLabel(l109);
		mv.visitLineNumber(223, l109);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/ParticleEffect", "SPELL", "Lcom/emoniph/witchery/util/ParticleEffect;");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/SoundEffect", "RANDOM_FIZZ", "Lcom/emoniph/witchery/util/SoundEffect;");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.6"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DCONST_1);
		mv.visitIntInsn(BIPUSH, 8);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/util/ParticleEffect", "send", "(Lcom/emoniph/witchery/util/SoundEffect;L"+aWorld+";DDDDDI)V", false);
		Label l119 = new Label();
		mv.visitLabel(l119);
		mv.visitLineNumber(224, l119);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETSTATIC, "net/minecraftforge/common/util/ForgeDirection", "UNKNOWN", "Lnet/minecraftforge/common/util/ForgeDirection;");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "getLiquidQuantity", "()I", false);
		mv.visitInsn(ICONST_1);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "drain", "(Lnet/minecraftforge/common/util/ForgeDirection;IZ)Lnet/minecraftforge/fluids/FluidStack;", false);
		mv.visitInsn(POP);
		Label l120 = new Label();
		mv.visitLabel(l120);
		mv.visitLineNumber(225, l120);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ritualTicks", "I");
		Label l121 = new Label();
		mv.visitLabel(l121);
		mv.visitLineNumber(226, l121);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "powered", "Z");
		Label l122 = new Label();
		mv.visitLabel(l122);
		mv.visitLineNumber(227, l122);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ticksHeated", "I");
		Label l123 = new Label();
		mv.visitLabel(l123);
		mv.visitLineNumber(228, l123);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 1);
		Label l124 = new Label();
		mv.visitLabel(l124);
		mv.visitLineNumber(229, l124);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitVarInsn(ILOAD, 17);
		mv.visitVarInsn(ILOAD, 20);
		Label l125 = new Label();
		mv.visitJumpInsn(IFEQ, l125);
		mv.visitInsn(ICONST_1);
		Label l126 = new Label();
		mv.visitJumpInsn(GOTO, l126);
		mv.visitLabel(l125);
		mv.visitFrame(Opcodes.F_FULL, 22, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, ""+aNBTTagCompound+"", Opcodes.INTEGER, "java/util/List", "java/util/List", Opcodes.INTEGER, "com/emoniph/witchery/common/IPowerSource", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.DOUBLE, Opcodes.INTEGER, ""+aAxisAlignedBB+"", "java/util/List", Opcodes.INTEGER, "com/emoniph/witchery/brewing/RitualStatus", Opcodes.INTEGER}, 2, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER});
		mv.visitInsn(ICONST_0);
		mv.visitLabel(l126);
		mv.visitFrame(Opcodes.F_FULL, 22, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, ""+aNBTTagCompound+"", Opcodes.INTEGER, "java/util/List", "java/util/List", Opcodes.INTEGER, "com/emoniph/witchery/common/IPowerSource", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.DOUBLE, Opcodes.INTEGER, ""+aAxisAlignedBB+"", "java/util/List", Opcodes.INTEGER, "com/emoniph/witchery/brewing/RitualStatus", Opcodes.INTEGER}, 3, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, Opcodes.INTEGER});
		mv.visitInsn(IADD);
		mv.visitVarInsn(ILOAD, 10);
		mv.visitMethodInsn(INVOKESPECIAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "checkForMisfortune", "(II)V", false);
		Label l127 = new Label();
		mv.visitLabel(l127);
		mv.visitLineNumber(230, l127);
		mv.visitJumpInsn(GOTO, l115);
		mv.visitLabel(l112);
		mv.visitLineNumber(233, l112);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/ParticleEffect", "SPELL_COLORED", "Lcom/emoniph/witchery/util/ParticleEffect;");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/SoundEffect", "RANDOM_POP", "Lcom/emoniph/witchery/util/SoundEffect;");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.6"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DCONST_1);
		mv.visitIntInsn(BIPUSH, 8);
		mv.visitLdcInsn(new Integer(-16742400));
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/util/ParticleEffect", "send", "(Lcom/emoniph/witchery/util/SoundEffect;L"+aWorld+";DDDDDII)V", false);
		Label l128 = new Label();
		mv.visitLabel(l128);
		mv.visitLineNumber(234, l128);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 22);
		Label l129 = new Label();
		mv.visitLabel(l129);
		mv.visitLineNumber(235, l129);
		mv.visitJumpInsn(GOTO, l115);
		mv.visitLabel(l113);
		mv.visitLineNumber(238, l113);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/ParticleEffect", "SPELL_COLORED", "Lcom/emoniph/witchery/util/ParticleEffect;");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/SoundEffect", "RANDOM_POP", "Lcom/emoniph/witchery/util/SoundEffect;");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.6"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DCONST_1);
		mv.visitIntInsn(BIPUSH, 8);
		mv.visitLdcInsn(new Integer(-16777080));
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/util/ParticleEffect", "send", "(Lcom/emoniph/witchery/util/SoundEffect;L"+aWorld+";DDDDDII)V", false);
		Label l130 = new Label();
		mv.visitLabel(l130);
		mv.visitLineNumber(239, l130);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 22);
		Label l131 = new Label();
		mv.visitLabel(l131);
		mv.visitLineNumber(240, l131);
		mv.visitJumpInsn(GOTO, l115);
		mv.visitLabel(l114);
		mv.visitLineNumber(243, l114);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/ParticleEffect", "SPELL_COLORED", "Lcom/emoniph/witchery/util/ParticleEffect;");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/SoundEffect", "RANDOM_POP", "Lcom/emoniph/witchery/util/SoundEffect;");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.6"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DCONST_1);
		mv.visitIntInsn(BIPUSH, 8);
		mv.visitLdcInsn(new Integer(-7864320));
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/util/ParticleEffect", "send", "(Lcom/emoniph/witchery/util/SoundEffect;L"+aWorld+";DDDDDII)V", false);
		Label l132 = new Label();
		mv.visitLabel(l132);
		mv.visitLineNumber(244, l132);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 22);
		Label l133 = new Label();
		mv.visitLabel(l133);
		mv.visitLineNumber(245, l133);
		mv.visitJumpInsn(GOTO, l115);
		mv.visitLabel(l111);
		mv.visitLineNumber(248, l111);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/ParticleEffect", "SPELL_COLORED", "Lcom/emoniph/witchery/util/ParticleEffect;");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/SoundEffect", "RANDOM_POP", "Lcom/emoniph/witchery/util/SoundEffect;");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.6"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DCONST_1);
		mv.visitIntInsn(BIPUSH, 8);
		mv.visitLdcInsn(new Integer(-7864184));
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/util/ParticleEffect", "send", "(Lcom/emoniph/witchery/util/SoundEffect;L"+aWorld+";DDDDDII)V", false);
		Label l134 = new Label();
		mv.visitLabel(l134);
		mv.visitLineNumber(249, l134);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 22);
		mv.visitLabel(l115);
		mv.visitLineNumber(253, l115);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ILOAD, 22);
		mv.visitJumpInsn(IFEQ, l55);
		Label l135 = new Label();
		mv.visitLabel(l135);
		mv.visitLineNumber(254, l135);
		mv.visitVarInsn(ALOAD, 4);
		mv.visitLdcInsn("Items");
		mv.visitIntInsn(BIPUSH, 10);
		mv.visitMethodInsn(INVOKEVIRTUAL, ""+aNBTTagCompound+"", "getTagList", "(Ljava/lang/String;I)L"+aNBTTagList+";", false);
		mv.visitVarInsn(ASTORE, 23);
		Label l136 = new Label();
		mv.visitLabel(l136);
		mv.visitLineNumber(255, l136);
		mv.visitVarInsn(ALOAD, 23);
		mv.visitVarInsn(ALOAD, 23);
		mv.visitMethodInsn(INVOKEVIRTUAL, ""+aNBTTagList+"", "tagCount", "()I", false);
		mv.visitInsn(ICONST_1);
		mv.visitInsn(ISUB);
		mv.visitMethodInsn(INVOKEVIRTUAL, ""+aNBTTagList+"", "getCompoundTagAt", "(I)L"+aNBTTagCompound+";", false);
		mv.visitMethodInsn(INVOKESTATIC, ""+aItemStack+"", "loadItemStackFromNBT", "(L"+aNBTTagCompound+";)L"+aItemStack+";", false);
		mv.visitVarInsn(ASTORE, 24);
		Label l137 = new Label();
		mv.visitLabel(l137);
		mv.visitLineNumber(256, l137);
		mv.visitVarInsn(ALOAD, 23);
		mv.visitVarInsn(ALOAD, 23);
		mv.visitMethodInsn(INVOKEVIRTUAL, ""+aNBTTagList+"", "tagCount", "()I", false);
		mv.visitInsn(ICONST_1);
		mv.visitInsn(ISUB);
		mv.visitMethodInsn(INVOKEVIRTUAL, ""+aNBTTagList+"", "removeTag", "(I)L"+aNBTBase+";", false);
		mv.visitInsn(POP);
		Label l138 = new Label();
		mv.visitLabel(l138);
		mv.visitLineNumber(257, l138);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitTypeInsn(NEW, ""+aEntityItem+"");
		mv.visitInsn(DUP);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitInsn(I2D);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitInsn(I2D);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitInsn(I2D);
		mv.visitVarInsn(ALOAD, 24);
		mv.visitMethodInsn(INVOKESPECIAL, ""+aEntityItem+"", "<init>", "(L"+aWorld+";DDDL"+aItemStack+";)V", false);
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/util/EntityUtil", "spawnEntityInWorld", "(L"+aWorld+";L"+aEntity+";)V", false);
		Label l139 = new Label();
		mv.visitLabel(l139);
		mv.visitLineNumber(258, l139);
		mv.visitVarInsn(ALOAD, 4);
		mv.visitLdcInsn("RitualTriggered");
		mv.visitInsn(ICONST_0);
		mv.visitMethodInsn(INVOKEVIRTUAL, ""+aNBTTagCompound+"", "setBoolean", "(Ljava/lang/String;Z)V", false);
		Label l140 = new Label();
		mv.visitLabel(l140);
		mv.visitLineNumber(259, l140);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ritualTicks", "I");
		Label l141 = new Label();
		mv.visitLabel(l141);
		mv.visitLineNumber(260, l141);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 1);
		Label l142 = new Label();
		mv.visitLabel(l142);
		mv.visitLineNumber(262, l142);
		mv.visitJumpInsn(GOTO, l55);
		mv.visitLabel(l97);
		mv.visitLineNumber(263, l97);
		mv.visitFrame(Opcodes.F_FULL, 17, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, ""+aNBTTagCompound+"", Opcodes.INTEGER, "java/util/List", "java/util/List", Opcodes.INTEGER, "com/emoniph/witchery/common/IPowerSource", Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.DOUBLE, Opcodes.INTEGER}, 0, new Object[] {});
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ritualTicks", "I");
		mv.visitIntInsn(BIPUSH, 21);
		mv.visitJumpInsn(IF_ICMPLE, l55);
		Label l143 = new Label();
		mv.visitLabel(l143);
		mv.visitLineNumber(264, l143);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETSTATIC, "net/minecraftforge/common/util/ForgeDirection", "UNKNOWN", "Lnet/minecraftforge/common/util/ForgeDirection;");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "getLiquidQuantity", "()I", false);
		mv.visitInsn(ICONST_1);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "drain", "(Lnet/minecraftforge/common/util/ForgeDirection;IZ)Lnet/minecraftforge/fluids/FluidStack;", false);
		mv.visitInsn(POP);
		Label l144 = new Label();
		mv.visitLabel(l144);
		mv.visitLineNumber(265, l144);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ritualTicks", "I");
		Label l145 = new Label();
		mv.visitLabel(l145);
		mv.visitLineNumber(266, l145);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "powered", "Z");
		Label l146 = new Label();
		mv.visitLabel(l146);
		mv.visitLineNumber(267, l146);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ticksHeated", "I");
		Label l147 = new Label();
		mv.visitLabel(l147);
		mv.visitLineNumber(268, l147);
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/ParticleEffect", "SPELL_COLORED", "Lcom/emoniph/witchery/util/ParticleEffect;");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/SoundEffect", "RANDOM_POP", "Lcom/emoniph/witchery/util/SoundEffect;");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.6"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DCONST_1);
		mv.visitIntInsn(BIPUSH, 8);
		mv.visitLdcInsn(new Integer(-7829504));
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/util/ParticleEffect", "send", "(Lcom/emoniph/witchery/util/SoundEffect;L"+aWorld+";DDDDDII)V", false);
		Label l148 = new Label();
		mv.visitLabel(l148);
		mv.visitLineNumber(269, l148);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 1);
		Label l149 = new Label();
		mv.visitLabel(l149);
		mv.visitLineNumber(273, l149);
		mv.visitJumpInsn(GOTO, l55);
		mv.visitLabel(l52);
		mv.visitLineNumber(275, l52);
		mv.visitFrame(Opcodes.F_FULL, 4, new Object[] {"com/emoniph/witchery/brewing/TileEntityCauldron", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER}, 0, new Object[] {});
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ritualTicks", "I");
		mv.visitIntInsn(BIPUSH, 20);
		Label l150 = new Label();
		mv.visitJumpInsn(IF_ICMPLE, l150);
		Label l151 = new Label();
		mv.visitLabel(l151);
		mv.visitLineNumber(276, l151);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETSTATIC, "net/minecraftforge/common/util/ForgeDirection", "UNKNOWN", "Lnet/minecraftforge/common/util/ForgeDirection;");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "getLiquidQuantity", "()I", false);
		mv.visitInsn(ICONST_1);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "drain", "(Lnet/minecraftforge/common/util/ForgeDirection;IZ)Lnet/minecraftforge/fluids/FluidStack;", false);
		mv.visitInsn(POP);
		Label l152 = new Label();
		mv.visitLabel(l152);
		mv.visitLineNumber(277, l152);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ritualTicks", "I");
		Label l153 = new Label();
		mv.visitLabel(l153);
		mv.visitLineNumber(278, l153);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "powered", "Z");
		Label l154 = new Label();
		mv.visitLabel(l154);
		mv.visitLineNumber(279, l154);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ticksHeated", "I");
		Label l155 = new Label();
		mv.visitLabel(l155);
		mv.visitLineNumber(280, l155);
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/ParticleEffect", "SPELL_COLORED", "Lcom/emoniph/witchery/util/ParticleEffect;");
		mv.visitFieldInsn(GETSTATIC, "com/emoniph/witchery/util/SoundEffect", "RANDOM_POP", "Lcom/emoniph/witchery/util/SoundEffect;");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "xCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "yCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.6"));
		mv.visitInsn(DADD);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "zCoord", "I");
		mv.visitInsn(I2D);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DADD);
		mv.visitLdcInsn(new Double("0.5"));
		mv.visitInsn(DCONST_1);
		mv.visitIntInsn(BIPUSH, 8);
		mv.visitLdcInsn(new Integer(-7829504));
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/util/ParticleEffect", "send", "(Lcom/emoniph/witchery/util/SoundEffect;L"+aWorld+";DDDDDII)V", false);
		Label l156 = new Label();
		mv.visitLabel(l156);
		mv.visitLineNumber(281, l156);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 1);
		mv.visitLabel(l150);
		mv.visitLineNumber(283, l150);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ritualTicks", "I");
		mv.visitLabel(l55);
		mv.visitLineNumber(285, l55);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/brewing/TileEntityCauldron", "ritualTicks", "I");
		mv.visitVarInsn(ILOAD, 3);
		mv.visitJumpInsn(IF_ICMPEQ, l49);
		Label l157 = new Label();
		mv.visitLabel(l157);
		mv.visitLineNumber(286, l157);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 1);
		mv.visitLabel(l49);
		mv.visitLineNumber(289, l49);
		mv.visitFrame(Opcodes.F_CHOP,1, null, 0, null);
		mv.visitVarInsn(ILOAD, 1);
		mv.visitJumpInsn(IFEQ, l2);
		Label l158 = new Label();
		mv.visitLabel(l158);
		mv.visitLineNumber(290, l158);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_1);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/brewing/TileEntityCauldron", "markBlockForUpdate", "(Z)V", false);
		mv.visitLabel(l2);
		mv.visitLineNumber(293, l2);
		mv.visitFrame(Opcodes.F_CHOP,2, null, 0, null);
		mv.visitInsn(RETURN);
		Label l159 = new Label();
		mv.visitLabel(l159);
		mv.visitLocalVariable("this", "Lcom/emoniph/witchery/brewing/TileEntityCauldron;", null, l0, l159, 0);
		mv.visitLocalVariable("sync", "Z", null, l4, l2, 1);
		mv.visitLocalVariable("thisBlock", "Lalkalus/main/core/util/BlockPos;", null, l5, l2, 2);
		mv.visitLocalVariable("heatSourceLevel", "I", null, l8, l13, 3);
		mv.visitLocalVariable("wasPowered", "Z", null, l18, l16, 3);
		mv.visitLocalVariable("power", "I", null, l19, l16, 4);
		mv.visitLocalVariable("source", "Lcom/emoniph/witchery/common/IPowerSource;", null, l26, l47, 5);
		mv.visitLocalVariable("powerNeeded", "D", null, l42, l27, 6);
		mv.visitLocalVariable("powerNeeded", "D", null, l43, l47, 6);
		mv.visitLocalVariable("small", "Z", null, l29, l42, 8);
		mv.visitLocalVariable("smallPower", "Z", null, l30, l42, 9);
		mv.visitLocalVariable("medium", "Z", null, l31, l42, 10);
		mv.visitLocalVariable("mediumPower", "Z", null, l32, l42, 11);
		mv.visitLocalVariable("powerScale", "D", null, l33, l42, 12);
		mv.visitLocalVariable("oldRitualTicks", "I", null, l51, l49, 3);
		mv.visitLocalVariable("nbtRoot", "L"+aNBTTagCompound+";", null, l54, l149, 4);
		mv.visitLocalVariable("witchCount", "I", null, l58, l149, 5);
		mv.visitLocalVariable("covenWitches", "Ljava/util/List;", "Ljava/util/List<Lcom/emoniph/witchery/entity/EntityCovenWitch;>;", l59, l149, 6);
		mv.visitLocalVariable("witch", "Lcom/emoniph/witchery/entity/EntityCovenWitch;", null, l62, l60, 7);
		mv.visitLocalVariable("playerWitches", "Ljava/util/List;", "Ljava/util/List<L"+aEntityPlayer+";>;", l65, l149, 7);
		mv.visitLocalVariable("playerCoven", "Z", null, l66, l149, 8);
		mv.visitLocalVariable("player", "L"+aEntityPlayer+";", null, l69, l67, 9);
		mv.visitLocalVariable("powerSource", "Lcom/emoniph/witchery/common/IPowerSource;", null, l76, l149, 9);
		mv.visitLocalVariable("neededPower", "I", null, l77, l149, 10);
		mv.visitLocalVariable("small2", "Z", null, l78, l149, 11);
		mv.visitLocalVariable("smallPower2", "Z", null, l79, l149, 12);
		mv.visitLocalVariable("medium2", "Z", null, l80, l149, 13);
		mv.visitLocalVariable("mediumPower2", "Z", null, l81, l149, 14);
		mv.visitLocalVariable("powerScale2", "D", null, l82, l149, 15);
		mv.visitLocalVariable("risk", "I", null, l87, l149, 17);
		mv.visitLocalVariable("bb", "L"+aAxisAlignedBB+";", null, l98, l142, 18);
		mv.visitLocalVariable("leonards", "Ljava/util/List;", "Ljava/util/List<Lcom/emoniph/witchery/entity/EntityLeonard;>;", l99, l142, 19);
		mv.visitLocalVariable("lenny", "Z", null, l100, l142, 20);
		mv.visitLocalVariable("leonard", "Lcom/emoniph/witchery/entity/EntityLeonard;", null, l103, l101, 21);
		mv.visitLocalVariable("status", "Lcom/emoniph/witchery/brewing/RitualStatus;", null, l107, l142, 21);
		mv.visitLocalVariable("failed", "Z", null, l108, l142, 22);
		mv.visitLocalVariable("nbtItems", "L"+aNBTTagList+";", null, l136, l142, 23);
		mv.visitLocalVariable("stack", "L"+aItemStack+";", null, l137, l142, 24);
		mv.visitMaxs(15, 25);
		mv.visitEnd();
		return true;
	}





	
	//public void sendTo(final IMessage message, final EntityPlayerMP/mw player)
	//public void sendTo(final Packet/ft packet, final EntityPlayer/yz player)
	//public void sendToDimension(final Packet packet, final World/ahb world)
	//public void sendToAllAround(final Packet packet, final World world, final NetworkRegistry.TargetPoint point)

	@Override
	public String[] getMethodNamesToStrip() {
		return new String[] {
				"updateEntity",
		};
	}

	@Override
	public String[] getMethodDescriptorsToStrip() {
		return null;
	}

	@Override
	public String getTransformerName() {
		return "Witches Cauldron Heating Fix";
	}

	@Override
	protected boolean runInjectorMultipleTimes() {
		return false;
	}

}
