package alkalus.main.asm.transformer;

import static org.objectweb.asm.Opcodes.AALOAD;
import static org.objectweb.asm.Opcodes.AASTORE;
import static org.objectweb.asm.Opcodes.ACC_PUBLIC;
import static org.objectweb.asm.Opcodes.ACONST_NULL;
import static org.objectweb.asm.Opcodes.ALOAD;
import static org.objectweb.asm.Opcodes.ARRAYLENGTH;
import static org.objectweb.asm.Opcodes.ASTORE;
import static org.objectweb.asm.Opcodes.BIPUSH;
import static org.objectweb.asm.Opcodes.DUP;
import static org.objectweb.asm.Opcodes.FCMPL;
import static org.objectweb.asm.Opcodes.FCONST_0;
import static org.objectweb.asm.Opcodes.FLOAD;
import static org.objectweb.asm.Opcodes.FSTORE;
import static org.objectweb.asm.Opcodes.GETFIELD;
import static org.objectweb.asm.Opcodes.GOTO;
import static org.objectweb.asm.Opcodes.ICONST_0;
import static org.objectweb.asm.Opcodes.ICONST_1;
import static org.objectweb.asm.Opcodes.ICONST_2;
import static org.objectweb.asm.Opcodes.IFEQ;
import static org.objectweb.asm.Opcodes.IFLT;
import static org.objectweb.asm.Opcodes.IFNE;
import static org.objectweb.asm.Opcodes.IFNONNULL;
import static org.objectweb.asm.Opcodes.IFNULL;
import static org.objectweb.asm.Opcodes.IF_ICMPEQ;
import static org.objectweb.asm.Opcodes.IF_ICMPLT;
import static org.objectweb.asm.Opcodes.IF_ICMPNE;
import static org.objectweb.asm.Opcodes.ILOAD;
import static org.objectweb.asm.Opcodes.INVOKEINTERFACE;
import static org.objectweb.asm.Opcodes.INVOKESPECIAL;
import static org.objectweb.asm.Opcodes.INVOKESTATIC;
import static org.objectweb.asm.Opcodes.INVOKEVIRTUAL;
import static org.objectweb.asm.Opcodes.ISTORE;
import static org.objectweb.asm.Opcodes.ISUB;
import static org.objectweb.asm.Opcodes.IXOR;
import static org.objectweb.asm.Opcodes.LCMP;
import static org.objectweb.asm.Opcodes.LCONST_0;
import static org.objectweb.asm.Opcodes.LREM;
import static org.objectweb.asm.Opcodes.NEW;
import static org.objectweb.asm.Opcodes.PUTFIELD;
import static org.objectweb.asm.Opcodes.RETURN;

import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

public class ClassTransformer_Witchery_TileEntityWitchesKettle extends BaseTransformer {

	public ClassTransformer_Witchery_TileEntityWitchesKettle(String transformedName, byte[] basicClass, boolean isObf) {
		super(transformedName, basicClass, isObf);
		init();
	}
	
	public final String aEntityPlayer = mObf ? "yz" : "net/minecraft/entity/player/EntityPlayer";
	public final String aWorld = mObf ? "ahb" : "net/minecraft/world/World";	
	public final String aItemStack = mObf ? "add" : "net/minecraft/item/ItemStack";

	public boolean injectMethod(String aMethodName, ClassWriter cw) {
		boolean[] aResults = new boolean[1];		
		aResults[0] = inject_updateEntity();
		for (boolean b : aResults) {
			if (!b) {
				log("Patching failed.");
				return false;
			}
		}	
		log("Patching Success.");	
		return true;
	}

	private boolean inject_updateEntity() {
		MethodVisitor mv;
		mv = getWriter().visitMethod(ACC_PUBLIC, "updateEntity", "()V", null, null);
		mv.visitCode();
		Label l0 = new Label();
		mv.visitLabel(l0);
		mv.visitLineNumber(312, l0);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKESPECIAL, "com/emoniph/witchery/blocks/TileEntityBase", "updateEntity", "()V", false);
		Label l1 = new Label();
		mv.visitLabel(l1);
		mv.visitLineNumber(313, l1);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "worldObj", "L"+aWorld+";");
		mv.visitFieldInsn(GETFIELD, ""+aWorld+"", "isRemote", "Z");
		Label l2 = new Label();
		mv.visitJumpInsn(IFNE, l2);
		Label l3 = new Label();
		mv.visitLabel(l3);
		mv.visitLineNumber(314, l3);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isRuined", "Z");
		mv.visitJumpInsn(IFNE, l2);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "ticks", "J");
		mv.visitLdcInsn(new Long(20L));
		mv.visitInsn(LREM);
		mv.visitInsn(LCONST_0);
		mv.visitInsn(LCMP);
		mv.visitJumpInsn(IFNE, l2);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isFilled", "()Z", false);
		mv.visitJumpInsn(IFEQ, l2);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "someFilled", "()Z", false);
		Label l4 = new Label();
		mv.visitJumpInsn(IFNE, l4);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "furnaceItemStacks", "[L"+aItemStack+";");
		mv.visitIntInsn(BIPUSH, 6);
		mv.visitInsn(AALOAD);
		mv.visitJumpInsn(IFNULL, l2);
		mv.visitLabel(l4);
		mv.visitLineNumber(315, l4);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitInsn(ICONST_0);
		mv.visitVarInsn(ISTORE, 1);
		Label l5 = new Label();
		mv.visitLabel(l5);
		mv.visitLineNumber(316, l5);
		mv.visitTypeInsn(NEW, "alkalus/main/core/util/BlockPos");
		mv.visitInsn(DUP);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "zCoord", "I");
		mv.visitMethodInsn(INVOKESPECIAL, "alkalus/main/core/util/BlockPos", "<init>", "(III)V", false);
		mv.visitVarInsn(ASTORE, 2);
		Label l6 = new Label();
		mv.visitLabel(l6);
		mv.visitLineNumber(317, l6);
		mv.visitVarInsn(ALOAD, 2);
		mv.visitMethodInsn(INVOKESTATIC, "alkalus/main/core/util/CauldronUtils", "hasFireBeneath", "(Lalkalus/main/core/util/BlockPos;)Z", false);
		mv.visitVarInsn(ISTORE, 3);
		Label l7 = new Label();
		mv.visitLabel(l7);
		mv.visitLineNumber(318, l7);
		mv.visitVarInsn(ILOAD, 3);
		Label l8 = new Label();
		mv.visitJumpInsn(IFNE, l8);
		Label l9 = new Label();
		mv.visitLabel(l9);
		mv.visitLineNumber(319, l9);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_1);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isRuined", "Z");
		Label l10 = new Label();
		mv.visitLabel(l10);
		mv.visitLineNumber(320, l10);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "color", "I");
		Label l11 = new Label();
		mv.visitLabel(l11);
		mv.visitLineNumber(321, l11);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "furnaceItemStacks", "[L"+aItemStack+";");
		mv.visitIntInsn(BIPUSH, 6);
		mv.visitInsn(ACONST_NULL);
		mv.visitInsn(AASTORE);
		Label l12 = new Label();
		mv.visitLabel(l12);
		mv.visitLineNumber(322, l12);
		Label l13 = new Label();
		mv.visitJumpInsn(GOTO, l13);
		mv.visitLabel(l8);
		mv.visitLineNumber(323, l8);
		mv.visitFrame(Opcodes.F_APPEND,3, new Object[] {Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER}, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "furnaceItemStacks", "[L"+aItemStack+";");
		mv.visitIntInsn(BIPUSH, 6);
		mv.visitInsn(AALOAD);
		mv.visitJumpInsn(IFNONNULL, l13);
		Label l14 = new Label();
		mv.visitLabel(l14);
		mv.visitLineNumber(324, l14);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "allFilled", "()Z", false);
		Label l15 = new Label();
		mv.visitJumpInsn(IFEQ, l15);
		Label l16 = new Label();
		mv.visitLabel(l16);
		mv.visitLineNumber(325, l16);
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/crafting/KettleRecipes", "instance", "()Lcom/emoniph/witchery/crafting/KettleRecipes;", false);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "furnaceItemStacks", "[L"+aItemStack+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "furnaceItemStacks", "[L"+aItemStack+";");
		mv.visitInsn(ARRAYLENGTH);
		mv.visitInsn(ICONST_2);
		mv.visitInsn(ISUB);
		mv.visitInsn(ICONST_0);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "worldObj", "L"+aWorld+";");
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/crafting/KettleRecipes", "getResult", "([L"+aItemStack+";IZL"+aWorld+";)Lcom/emoniph/witchery/crafting/KettleRecipes$KettleRecipe;", false);
		mv.visitVarInsn(ASTORE, 4);
		Label l17 = new Label();
		mv.visitLabel(l17);
		mv.visitLineNumber(326, l17);
		mv.visitVarInsn(ALOAD, 4);
		Label l18 = new Label();
		mv.visitJumpInsn(IFNONNULL, l18);
		Label l19 = new Label();
		mv.visitLabel(l19);
		mv.visitLineNumber(327, l19);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "color", "I");
		Label l20 = new Label();
		mv.visitLabel(l20);
		mv.visitLineNumber(328, l20);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_1);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isRuined", "Z");
		Label l21 = new Label();
		mv.visitLabel(l21);
		mv.visitLineNumber(329, l21);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "furnaceItemStacks", "[L"+aItemStack+";");
		mv.visitIntInsn(BIPUSH, 6);
		mv.visitInsn(ACONST_NULL);
		mv.visitInsn(AASTORE);
		Label l22 = new Label();
		mv.visitLabel(l22);
		mv.visitLineNumber(330, l22);
		mv.visitJumpInsn(GOTO, l13);
		mv.visitLabel(l18);
		mv.visitLineNumber(331, l18);
		mv.visitFrame(Opcodes.F_APPEND,1, new Object[] {"com/emoniph/witchery/crafting/KettleRecipes$KettleRecipe"}, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitVarInsn(ALOAD, 4);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/crafting/KettleRecipes$KettleRecipe", "getColor", "()I", false);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "color", "I");
		Label l23 = new Label();
		mv.visitLabel(l23);
		mv.visitLineNumber(332, l23);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isPowered", "Z");
		mv.visitVarInsn(ISTORE, 5);
		Label l24 = new Label();
		mv.visitLabel(l24);
		mv.visitLineNumber(333, l24);
		mv.visitVarInsn(ALOAD, 4);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/crafting/KettleRecipes$KettleRecipe", "getRequiredPower", "()F", false);
		mv.visitVarInsn(FSTORE, 6);
		Label l25 = new Label();
		mv.visitLabel(l25);
		mv.visitLineNumber(334, l25);
		mv.visitVarInsn(FLOAD, 6);
		mv.visitInsn(FCONST_0);
		mv.visitInsn(FCMPL);
		Label l26 = new Label();
		mv.visitJumpInsn(IFNE, l26);
		Label l27 = new Label();
		mv.visitLabel(l27);
		mv.visitLineNumber(335, l27);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_1);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isPowered", "Z");
		Label l28 = new Label();
		mv.visitLabel(l28);
		mv.visitLineNumber(336, l28);
		Label l29 = new Label();
		mv.visitJumpInsn(GOTO, l29);
		mv.visitLabel(l26);
		mv.visitLineNumber(337, l26);
		mv.visitFrame(Opcodes.F_APPEND,2, new Object[] {Opcodes.INTEGER, Opcodes.FLOAT}, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "zCoord", "I");
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/blocks/BlockKettle", "access$0", "(L"+aWorld+";III)Lcom/emoniph/witchery/common/IPowerSource;", false);
		mv.visitVarInsn(ASTORE, 7);
		Label l30 = new Label();
		mv.visitLabel(l30);
		mv.visitLineNumber(338, l30);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitVarInsn(ALOAD, 7);
		Label l31 = new Label();
		mv.visitJumpInsn(IFNULL, l31);
		mv.visitVarInsn(ALOAD, 7);
		mv.visitVarInsn(FLOAD, 6);
		mv.visitMethodInsn(INVOKEINTERFACE, "com/emoniph/witchery/common/IPowerSource", "consumePower", "(F)Z", true);
		mv.visitJumpInsn(IFEQ, l31);
		mv.visitInsn(ICONST_1);
		Label l32 = new Label();
		mv.visitJumpInsn(GOTO, l32);
		mv.visitLabel(l31);
		mv.visitFrame(Opcodes.F_FULL, 8, new Object[] {"com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, "com/emoniph/witchery/crafting/KettleRecipes$KettleRecipe", Opcodes.INTEGER, Opcodes.FLOAT, "com/emoniph/witchery/common/IPowerSource"}, 1, new Object[] {"com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle"});
		mv.visitInsn(ICONST_0);
		mv.visitLabel(l32);
		mv.visitFrame(Opcodes.F_FULL, 8, new Object[] {"com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, "com/emoniph/witchery/crafting/KettleRecipes$KettleRecipe", Opcodes.INTEGER, Opcodes.FLOAT, "com/emoniph/witchery/common/IPowerSource"}, 2, new Object[] {"com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", Opcodes.INTEGER});
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isPowered", "Z");
		mv.visitLabel(l29);
		mv.visitLineNumber(340, l29);
		mv.visitFrame(Opcodes.F_CHOP,1, null, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isPowered", "Z");
		Label l33 = new Label();
		mv.visitJumpInsn(IFEQ, l33);
		Label l34 = new Label();
		mv.visitLabel(l34);
		mv.visitLineNumber(341, l34);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "furnaceItemStacks", "[L"+aItemStack+";");
		mv.visitIntInsn(BIPUSH, 6);
		mv.visitVarInsn(ALOAD, 4);
		mv.visitInsn(ACONST_NULL);
		mv.visitInsn(ICONST_1);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/crafting/KettleRecipes$KettleRecipe", "getOutput", "(L"+aEntityPlayer+";Z)L"+aItemStack+";", false);
		mv.visitInsn(AASTORE);
		Label l35 = new Label();
		mv.visitLabel(l35);
		mv.visitLineNumber(342, l35);
		mv.visitInsn(ICONST_0);
		mv.visitVarInsn(ISTORE, 7);
		Label l36 = new Label();
		mv.visitLabel(l36);
		Label l37 = new Label();
		mv.visitJumpInsn(GOTO, l37);
		Label l38 = new Label();
		mv.visitLabel(l38);
		mv.visitLineNumber(343, l38);
		mv.visitFrame(Opcodes.F_APPEND,1, new Object[] {Opcodes.INTEGER}, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "furnaceItemStacks", "[L"+aItemStack+";");
		mv.visitVarInsn(ILOAD, 7);
		mv.visitInsn(ACONST_NULL);
		mv.visitInsn(AASTORE);
		Label l39 = new Label();
		mv.visitLabel(l39);
		mv.visitLineNumber(342, l39);
		mv.visitIincInsn(7, 1);
		mv.visitLabel(l37);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ILOAD, 7);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "furnaceItemStacks", "[L"+aItemStack+";");
		mv.visitInsn(ARRAYLENGTH);
		mv.visitInsn(ICONST_2);
		mv.visitInsn(ISUB);
		mv.visitJumpInsn(IF_ICMPLT, l38);
		mv.visitLabel(l33);
		mv.visitLineNumber(345, l33);
		mv.visitFrame(Opcodes.F_CHOP,1, null, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isPowered", "Z");
		Label l40 = new Label();
		mv.visitJumpInsn(IFNE, l40);
		mv.visitVarInsn(ILOAD, 5);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isPowered", "Z");
		mv.visitJumpInsn(IF_ICMPNE, l40);
		mv.visitInsn(ICONST_0);
		Label l41 = new Label();
		mv.visitJumpInsn(GOTO, l41);
		mv.visitLabel(l40);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitInsn(ICONST_1);
		mv.visitLabel(l41);
		mv.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[] {Opcodes.INTEGER});
		mv.visitVarInsn(ISTORE, 1);
		Label l42 = new Label();
		mv.visitLabel(l42);
		mv.visitLineNumber(347, l42);
		mv.visitJumpInsn(GOTO, l13);
		mv.visitLabel(l15);
		mv.visitLineNumber(348, l15);
		mv.visitFrame(Opcodes.F_CHOP,3, null, 0, null);
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/crafting/KettleRecipes", "instance", "()Lcom/emoniph/witchery/crafting/KettleRecipes;", false);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "furnaceItemStacks", "[L"+aItemStack+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "furnaceItemStacks", "[L"+aItemStack+";");
		mv.visitInsn(ARRAYLENGTH);
		mv.visitInsn(ICONST_2);
		mv.visitInsn(ISUB);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "worldObj", "L"+aWorld+";");
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/crafting/KettleRecipes", "getResult", "([L"+aItemStack+";IZL"+aWorld+";)Lcom/emoniph/witchery/crafting/KettleRecipes$KettleRecipe;", false);
		mv.visitVarInsn(ASTORE, 4);
		Label l43 = new Label();
		mv.visitLabel(l43);
		mv.visitLineNumber(349, l43);
		mv.visitVarInsn(ALOAD, 4);
		Label l44 = new Label();
		mv.visitJumpInsn(IFNULL, l44);
		mv.visitVarInsn(ALOAD, 4);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/crafting/KettleRecipes$KettleRecipe", "getColor", "()I", false);
		Label l45 = new Label();
		mv.visitJumpInsn(IFNE, l45);
		mv.visitLabel(l44);
		mv.visitLineNumber(350, l44);
		mv.visitFrame(Opcodes.F_APPEND,1, new Object[] {"com/emoniph/witchery/crafting/KettleRecipes$KettleRecipe"}, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_0);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "color", "I");
		Label l46 = new Label();
		mv.visitLabel(l46);
		mv.visitLineNumber(351, l46);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_1);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isRuined", "Z");
		Label l47 = new Label();
		mv.visitLabel(l47);
		mv.visitLineNumber(352, l47);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "furnaceItemStacks", "[L"+aItemStack+";");
		mv.visitIntInsn(BIPUSH, 6);
		mv.visitInsn(ACONST_NULL);
		mv.visitInsn(AASTORE);
		Label l48 = new Label();
		mv.visitLabel(l48);
		mv.visitLineNumber(353, l48);
		Label l49 = new Label();
		mv.visitJumpInsn(GOTO, l49);
		mv.visitLabel(l45);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ALOAD, 4);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/crafting/KettleRecipes$KettleRecipe", "getColor", "()I", false);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "color", "I");
		mv.visitJumpInsn(IF_ICMPEQ, l49);
		Label l50 = new Label();
		mv.visitLabel(l50);
		mv.visitLineNumber(354, l50);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitVarInsn(ALOAD, 4);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/crafting/KettleRecipes$KettleRecipe", "getColor", "()I", false);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "color", "I");
		Label l51 = new Label();
		mv.visitLabel(l51);
		mv.visitLineNumber(355, l51);
		mv.visitInsn(ICONST_1);
		mv.visitVarInsn(ISTORE, 1);
		mv.visitLabel(l49);
		mv.visitLineNumber(357, l49);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isRuined", "Z");
		mv.visitJumpInsn(IFNE, l13);
		Label l52 = new Label();
		mv.visitLabel(l52);
		mv.visitLineNumber(358, l52);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isPowered", "Z");
		mv.visitVarInsn(ISTORE, 5);
		Label l53 = new Label();
		mv.visitLabel(l53);
		mv.visitLineNumber(359, l53);
		mv.visitVarInsn(ALOAD, 4);
		mv.visitMethodInsn(INVOKEVIRTUAL, "com/emoniph/witchery/crafting/KettleRecipes$KettleRecipe", "getRequiredPower", "()F", false);
		mv.visitVarInsn(FSTORE, 6);
		Label l54 = new Label();
		mv.visitLabel(l54);
		mv.visitLineNumber(360, l54);
		mv.visitVarInsn(FLOAD, 6);
		mv.visitInsn(FCONST_0);
		mv.visitInsn(FCMPL);
		Label l55 = new Label();
		mv.visitJumpInsn(IFNE, l55);
		Label l56 = new Label();
		mv.visitLabel(l56);
		mv.visitLineNumber(361, l56);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitInsn(ICONST_1);
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isPowered", "Z");
		Label l57 = new Label();
		mv.visitLabel(l57);
		mv.visitLineNumber(362, l57);
		Label l58 = new Label();
		mv.visitJumpInsn(GOTO, l58);
		mv.visitLabel(l55);
		mv.visitLineNumber(363, l55);
		mv.visitFrame(Opcodes.F_APPEND,2, new Object[] {Opcodes.INTEGER, Opcodes.FLOAT}, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "zCoord", "I");
		mv.visitMethodInsn(INVOKESTATIC, "com/emoniph/witchery/blocks/BlockKettle", "access$0", "(L"+aWorld+";III)Lcom/emoniph/witchery/common/IPowerSource;", false);
		mv.visitVarInsn(ASTORE, 7);
		Label l59 = new Label();
		mv.visitLabel(l59);
		mv.visitLineNumber(364, l59);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitVarInsn(ALOAD, 7);
		Label l60 = new Label();
		mv.visitJumpInsn(IFNULL, l60);
		mv.visitVarInsn(ALOAD, 7);
		mv.visitMethodInsn(INVOKEINTERFACE, "com/emoniph/witchery/common/IPowerSource", "getCurrentPower", "()F", true);
		mv.visitVarInsn(FLOAD, 6);
		mv.visitInsn(FCMPL);
		mv.visitJumpInsn(IFLT, l60);
		mv.visitInsn(ICONST_1);
		Label l61 = new Label();
		mv.visitJumpInsn(GOTO, l61);
		mv.visitLabel(l60);
		mv.visitFrame(Opcodes.F_FULL, 8, new Object[] {"com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, "com/emoniph/witchery/crafting/KettleRecipes$KettleRecipe", Opcodes.INTEGER, Opcodes.FLOAT, "com/emoniph/witchery/common/IPowerSource"}, 1, new Object[] {"com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle"});
		mv.visitInsn(ICONST_0);
		mv.visitLabel(l61);
		mv.visitFrame(Opcodes.F_FULL, 8, new Object[] {"com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", Opcodes.INTEGER, "alkalus/main/core/util/BlockPos", Opcodes.INTEGER, "com/emoniph/witchery/crafting/KettleRecipes$KettleRecipe", Opcodes.INTEGER, Opcodes.FLOAT, "com/emoniph/witchery/common/IPowerSource"}, 2, new Object[] {"com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", Opcodes.INTEGER});
		mv.visitFieldInsn(PUTFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isPowered", "Z");
		mv.visitLabel(l58);
		mv.visitLineNumber(366, l58);
		mv.visitFrame(Opcodes.F_CHOP,1, null, 0, null);
		mv.visitVarInsn(ILOAD, 5);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isPowered", "Z");
		mv.visitInsn(IXOR);
		mv.visitVarInsn(ISTORE, 1);
		mv.visitLabel(l13);
		mv.visitLineNumber(370, l13);
		mv.visitFrame(Opcodes.F_CHOP,3, null, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "isRuined", "Z");
		Label l62 = new Label();
		mv.visitJumpInsn(IFNE, l62);
		mv.visitVarInsn(ILOAD, 1);
		mv.visitJumpInsn(IFEQ, l2);
		mv.visitLabel(l62);
		mv.visitLineNumber(371, l62);
		mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "worldObj", "L"+aWorld+";");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "xCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "yCoord", "I");
		mv.visitVarInsn(ALOAD, 0);
		mv.visitFieldInsn(GETFIELD, "com/emoniph/witchery/blocks/BlockKettle$TileEntityKettle", "zCoord", "I");
		mv.visitMethodInsn(INVOKEVIRTUAL, ""+aWorld+"", "markBlockForUpdate", "(III)V", false);
		mv.visitLabel(l2);
		mv.visitLineNumber(373, l2);
		mv.visitFrame(Opcodes.F_CHOP,3, null, 0, null);
		mv.visitInsn(RETURN);
		Label l63 = new Label();
		mv.visitLabel(l63);
		mv.visitLocalVariable("this", "Lcom/emoniph/witchery/blocks/BlockKettle$TileEntityKettle;", null, l0, l63, 0);
		mv.visitLocalVariable("sendPacket", "Z", null, l5, l2, 1);
		mv.visitLocalVariable("thisBlock", "Lalkalus/main/core/util/BlockPos;", null, l6, l2, 2);
		mv.visitLocalVariable("hasHeatBelow", "Z", null, l7, l2, 3);
		mv.visitLocalVariable("recipe", "Lcom/emoniph/witchery/crafting/KettleRecipes$KettleRecipe;", null, l17, l42, 4);
		mv.visitLocalVariable("wasPowered", "Z", null, l24, l42, 5);
		mv.visitLocalVariable("powerNeeded", "F", null, l25, l42, 6);
		mv.visitLocalVariable("powerSource", "Lcom/emoniph/witchery/common/IPowerSource;", null, l30, l29, 7);
		mv.visitLocalVariable("i", "I", null, l36, l33, 7);
		mv.visitLocalVariable("recipe", "Lcom/emoniph/witchery/crafting/KettleRecipes$KettleRecipe;", null, l43, l13, 4);
		mv.visitLocalVariable("wasPowered", "Z", null, l53, l13, 5);
		mv.visitLocalVariable("powerNeeded", "F", null, l54, l13, 6);
		mv.visitLocalVariable("powerSource", "Lcom/emoniph/witchery/common/IPowerSource;", null, l59, l58, 7);
		mv.visitMaxs(5, 8);
		mv.visitEnd();
		
		
		return true;
	}

	@Override
	public String[] getMethodNamesToStrip() {
		return new String[] {
				"updateEntity",
		};
	}

	@Override
	public String[] getMethodDescriptorsToStrip() {
		return null;
	}

	@Override
	public String getTransformerName() {
		return "Witches Kettle Heating Fix";
	}

	@Override
	protected boolean runInjectorMultipleTimes() {
		return false;
	}

}
